# Generated by Django 5.0.7 on 2025-09-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('processor', models.CharField(blank=True, max_length=100, null=True)),
                ('memory', models.CharField(blank=True, max_length=100, null=True)),
                ('storage', models.CharField(blank=True, max_length=100, null=True)),
                ('display', models.CharField(blank=True, max_length=100, null=True)),
                ('graphics', models.CharField(blank=True, max_length=100, null=True)),
                ('cooling', models.CharField(blank=True, max_length=100, null=True)),
                ('cooling_type', models.CharField(blank=True, max_length=100, null=True)),
                ('display_type', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('refresh_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('connectivity', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('switch_type', models.CharField(blank=True, max_length=100, null=True)),
                ('lighting', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dpi', models.CharField(blank=True, max_length=50, null=True)),
                ('buttons', models.CharField(blank=True, max_length=100, null=True)),
                ('chipset', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('read_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('write_speed', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('features', models.CharField(blank=True, max_length=200, null=True)),
                ('ports', models.CharField(blank=True, max_length=50, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=200, null=True)),
                ('length', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
